package updates

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"os"
	"path/filepath"

	"github.com/AegisAgentAscalon/aegis-core/internal/filepersist"
)

func (s *store) beginBlob(ctx context.Context, filename string) (string, string, error) {
	if !validArtifactFilename(filename) {
		return "", "", ErrInvalidManifest
	}
	if err := filepersist.EnsureDir(ctx, s.blobDir()); err != nil {
		return "", "", persistenceError(err)
	}
	var random [16]byte
	for attempt := 0; attempt < 4; attempt++ {
		if _, err := rand.Read(random[:]); err != nil {
			return "", "", ErrStorageUnavailable
		}
		id := hex.EncodeToString(random[:])
		if err := os.Mkdir(filepath.Join(s.blobDir(), id), 0700); err == nil {
			return id, s.blobPath(id, filename), nil
		} else if !errors.Is(err, os.ErrExist) {
			return "", "", ErrStorageUnavailable
		}
	}
	return "", "", ErrStorageUnavailable
}

func (s *store) finishBlob(ctx context.Context, id, filename, role string) (blobRecord, error) {
	if !validBlobID(id) || !validArtifactFilename(filename) {
		return blobRecord{}, ErrStorageUnavailable
	}
	f, err := filepersist.OpenRegular(ctx, s.blobPath(id, filename))
	if err != nil {
		return blobRecord{}, persistenceError(err)
	}
	hash := sha256.New()
	n, err := io.Copy(hash, contextReader{ctx, f})
	err = errors.Join(err, f.Close())
	if err != nil {
		return blobRecord{}, persistenceError(err)
	}
	return blobRecord{Filename: filename, Role: role, Size: n, SHA256: hex.EncodeToString(hash.Sum(nil))}, nil
}

func (s *store) copyBlob(ctx context.Context, source, filename, role string, prepared *[]string) (string, blobRecord, error) {
	id, target, err := s.beginBlob(ctx, filename)
	if err != nil {
		return "", blobRecord{}, err
	}
	*prepared = append(*prepared, id)
	if err := copyFileAtomic(ctx, source, target); err != nil {
		return "", blobRecord{}, err
	}
	blob, err := s.finishBlob(ctx, id, filename, role)
	return id, blob, err
}

// IDs are generated by this operation. Published blobs are never collected here.
func (s *store) discardPrepared(ids []string) {
	for _, id := range ids {
		if validBlobID(id) {
			_ = os.RemoveAll(filepath.Join(s.blobDir(), id))
		}
	}
}

func (s *store) prepareLegacy(ctx context.Context, cfg AppConfig, v *stateView, prepared *[]string) error {
	if err := s.resolveLegacyStage(ctx, cfg, v); err != nil {
		return err
	}

	invalid, err := s.candidateProblem(ctx, v)
	if err != nil {
		return err
	}
	if invalid {
		v.quarantineCandidate()
	}
	if err := contextError(ctx); err != nil {
		return err
	}
	if v.blobs == nil {
		v.blobs = make(map[string]blobRecord)
	}
	copyTransfer := func(d downloadedUpdate) (downloadedUpdate, error) {
		if d.blobID != "" {
			return d, nil
		}
		id, blob, err := s.copyBlob(ctx, d.ArtifactPath, d.Artifact.Filename, "download", prepared)
		if err != nil {
			return d, err
		}
		if blob.Size != d.BytesWritten {
			return d, ErrVerificationFailed
		}
		v.blobs[id] = blob
		d.blobID, d.ArtifactPath = id, s.blobPath(id, d.Artifact.Filename)
		return d, nil
	}
	if v.downloaded.value != nil {
		d, err := copyTransfer(*v.downloaded.value)
		if err != nil {
			return err
		}
		v.downloaded = stored(d)
	}
	if v.verified.value != nil {
		verified := *v.verified.value
		d, err := copyTransfer(verified.Downloaded)
		if err != nil {
			return err
		}
		verified.Downloaded = d
		v.verified = stored(verified)
	}
	if v.staged.value != nil && v.staged.value.blobID == "" {
		r := *v.staged.value
		id, blob, err := s.copyBlob(ctx, r.ArtifactPath, r.ArtifactName, "staged", prepared)
		if err != nil {
			return err
		}
		if blob.Size != r.Size {
			return ErrVerificationFailed
		}
		v.blobs[id] = blob
		r.blobID, r.ArtifactPath = id, s.blobPath(id, r.ArtifactName)
		v.staged = stored(r)
	}
	return nil
}

func verifiedDownload(v *verifiedUpdate) *downloadedUpdate {
	if v == nil {
		return nil
	}
	return &v.Downloaded
}

func (s *store) candidateProblem(ctx context.Context, v *stateView) (bool, error) {
	invalid := v.candidateFault || v.selected.err != nil || v.downloaded.err != nil || v.verified.err != nil
	if item := v.selected.value; item != nil && !structuralSelected(*item) {
		invalid = true
	}
	checkTransfer := func(d downloadedUpdate) error {
		if err := s.structuralDownloaded(s.downloadedPathFor(d), d); err != nil {
			return err
		}
		f, err := filepersist.OpenRegular(ctx, d.ArtifactPath)
		if err != nil {
			return err
		}
		return f.Close()
	}
	for _, item := range []*downloadedUpdate{v.downloaded.value, verifiedDownload(v.verified.value)} {
		if item == nil {
			continue
		}
		if err := checkTransfer(*item); err != nil {
			if errors.Is(err, filepersist.ErrUnsafePath) || contextError(ctx) != nil {
				return false, persistenceError(err)
			}
			if !errors.Is(err, ErrStorageUnavailable) && !errors.Is(err, ErrVerificationFailed) && !errors.Is(err, os.ErrNotExist) {
				return false, persistenceError(err)
			}
			invalid = true
		}
	}
	if item := v.verified.value; item != nil && (item.SchemaVersion != schemaVersion || item.VerifiedAt.IsZero()) {
		invalid = true
	}
	return invalid, nil
}

func (s *store) resolveLegacyStage(ctx context.Context, cfg AppConfig, v *stateView) error {
	if v.fatal != nil {
		return v.fatal
	}
	// Resolve independent staged authority before a broken candidate is removed.
	if v.staged.err != nil || v.lifecycle.err != nil {
		return ErrStorageUnavailable
	}
	if v.staged.value != nil {
		r, err := v.stagedFor(cfg)
		if err != nil {
			return err
		}
		if _, err := stagedArtifact(r); err != nil {
			return err
		}
		if !samePath(r.ArtifactPath, s.stagedPathFor(r)) {
			return ErrStorageUnavailable
		}
		if r.blobID == "" {
			f, err := filepersist.OpenRegular(ctx, r.ArtifactPath)
			if err != nil {
				return persistenceError(err)
			}
			info, statErr := f.Stat()
			closeErr := f.Close()
			if statErr != nil || closeErr != nil || info.Size() != r.Size {
				return ErrVerificationFailed
			}
		}
		if v.lifecycle.value != nil && validateLifecycleRecord(*v.lifecycle.value, r.StagedUpdate) != nil {
			return ErrStorageUnavailable
		}
		v.staged = stored(r)
	} else if v.lifecycle.value != nil {
		return ErrStorageUnavailable
	}

	return nil
}
